[package]
name = "filter_rust"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = { version = "*", features = ["derive"] }
serde_json = "1.0"
serde_bytes = "0.11"
rmp-serde = "1.1"
libc = "0.2"
regex = "1.7"

[dev-dependencies]
test-case = "3.0.0"
